use anyhow::{Result, Context};
use serde::{Deserialize, Serialize};
use std::fs;
use colored::Colorize;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Config {
    pub gemini_api_key: String,
    pub mongodb_url: String,
    pub mongodb_db: String,
    pub mongodb_collection: String,
    pub log_level: String,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            gemini_api_key: String::new(),
            mongodb_url: "mongodb://localhost:27017/".to_string(),
            mongodb_db: "git_whisperer_db".to_string(),
            mongodb_collection: "project_history".to_string(),
            log_level: "INFO".to_string(),
        }
    }
}

impl Config {
    pub fn load() -> Result<Self> {
        dotenv::dotenv().ok();
        
        let gemini_api_key = std::env::var("GEMINI_API_KEY")
            .context("GEMINI_API_KEY not found in environment")?;
        
        let mongodb_url = std::env::var("MONGODB_URL")
            .unwrap_or_else(|_| "mongodb://localhost:27017/".to_string());
        
        let mongodb_db = std::env::var("MONGODB_DB")
            .unwrap_or_else(|_| "git_whisperer_db".to_string());
        
        let mongodb_collection = std::env::var("MONGODB_COLLECTION")
            .unwrap_or_else(|_| "project_history".to_string());
        
        let log_level = std::env::var("LOG_LEVEL")
            .unwrap_or_else(|_| "INFO".to_string());
        
        Ok(Self {
            gemini_api_key,
            mongodb_url,
            mongodb_db,
            mongodb_collection,
            log_level,
        })
    }
    
    pub fn load_or_default() -> Result<Self> {
        dotenv::dotenv().ok();
        
        let gemini_api_key = std::env::var("GEMINI_API_KEY").unwrap_or_default();
        let mongodb_url = std::env::var("MONGODB_URL")
            .unwrap_or_else(|_| "mongodb://localhost:27017/".to_string());
        let mongodb_db = std::env::var("MONGODB_DB")
            .unwrap_or_else(|_| "git_whisperer_db".to_string());
        let mongodb_collection = std::env::var("MONGODB_COLLECTION")
            .unwrap_or_else(|_| "project_history".to_string());
        let log_level = std::env::var("LOG_LEVEL")
            .unwrap_or_else(|_| "INFO".to_string());
        
        Ok(Self {
            gemini_api_key,
            mongodb_url,
            mongodb_db,
            mongodb_collection,
            log_level,
        })
    }
    
    pub async fn load_or_setup() -> Result<Self> {
        let config = Self::load_or_default()?;
        
        // Check if setup is needed - only if API key is missing
        if config.gemini_api_key.is_empty() {
            println!();
            println!("{}", "╔═══════════════════════════════════════╗".bright_yellow());
            println!("{}", "║           ⚠️  Setup Required          ║".bright_yellow().bold());
            println!("{}", "║                                       ║".bright_yellow());
            println!("{}", "║ Configuration incomplete. Starting    ║".bright_yellow());
            println!("{}", "║ setup wizard...                       ║".bright_yellow());
            println!("{}", "╚═══════════════════════════════════════╝".bright_yellow());
            println!();
            crate::cli::setup::run_setup().await?;
            // Reload after setup
            return Self::load();
        }
        
        Ok(config)
    }
    
    pub fn save(&self) -> Result<()> {
        let env_content = format!(
            "# Git Whisperer Configuration\n\
             # Auto-generated by setup process\n\n\
             GEMINI_API_KEY={}\n\
             MONGODB_URL={}\n\
             MONGODB_DB={}\n\
             MONGODB_COLLECTION={}\n\
             LOG_LEVEL={}\n",
            self.gemini_api_key,
            self.mongodb_url,
            self.mongodb_db,
            self.mongodb_collection,
            self.log_level
        );
        
        fs::write(".env", env_content)?;
        Ok(())
    }
}
